'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { spawnSync: defaultSpawnSync } = require('node:child_process');
const { checkProject, collectProject, hasErrors, pcfprojBuildMode } = require('./pcf-doctor.js');
const { findControlProject } = require('./pcf-build.js');
const { dependencySet, loadMatrix } = require('./pcf-matrix.js');
const { parseManifest } = require('./pcf-manifest.js');
const { runNpm: defaultRunNpm } = require('./node-tool.js');

const BEST_PRACTICES = 'references/pcf-best-practices.md';
const UPGRADE_FLOW = 'skills/pcf/upgrade-flow.md';
const SAFE_APPLY = new Set(['DEPS_TO_MATRIX', 'BUILDMODE_PRODUCTION', 'PLATFORM_LIB_VERSION', 'REINSTALL']);

function planUpgrade(state, matrix = loadMatrix(), options = {}) {
  const hosts = options.hosts || ['model'];
  const findings = checkProject(state, matrix, { hosts, needs: ['build'], platform: options.platform || process.platform });
  const steps = [];
  const manual = [];
  const family = dependencyFamily(state);
  let needsReinstall = false;

  addManualNotes(state, hosts, manual);

  const packageStep = packageJsonStep(state, matrix, family);
  if (packageStep) {
    steps.push(packageStep);
    needsReinstall = true;
  }

  const buildStep = buildModeStep(state);
  if (buildStep) steps.push(buildStep);

  steps.push(...platformLibrarySteps(state, matrix));
  if (needsReinstall) {
    steps.push({
      id: 'REINSTALL',
      file: 'package-lock.json',
      why: 'Refresh package-lock.json after package.json is pinned to the PCF compatibility matrix.',
    });
  }

  if (findings.some((finding) => finding.id === 'PROJ_ESLINT_LEGACY')) {
    manual.push({
      id: 'ESLINT_FLAT_CONFIG',
      why: 'This release never replaces or deletes an existing ESLint config automatically; add eslint.config.mjs from the generated template, verify lint, then remove legacy .eslintrc files yourself.',
      refs: [BEST_PRACTICES, UPGRADE_FLOW],
    });
  }

  if (Array.isArray(state.missingFeatures) && state.missingFeatures.length) {
    manual.push({
      id: 'DECLARE_FEATURES',
      why: `Declare missing feature usage manually with required="false": ${state.missingFeatures.join(', ')}.`,
      refs: [BEST_PRACTICES, UPGRADE_FLOW],
    });
  }

  return { steps, manual };
}

function dependencyFamily(state) {
  if (state.family === 'standard' || state.family === 'virtual') return state.family;
  // Task 9 owns this rule but does not currently export it. Keep this fallback deliberately identical
  // to the doctor's documented state shape (manifestModels[].control.controlType) and call out the
  // missing export in the task report, rather than introducing package-name heuristics that could
  // diverge from the doctor for hand-built projects.
  return (state.manifestModels || []).some((model) => model && model.control && model.control.controlType === 'virtual')
    ? 'virtual'
    : 'standard';
}

function packageJsonStep(state, matrix, family) {
  if (!state.packageJsonText) return null;
  const expected = dependencySet(matrix, family);
  const apply = (text) => rewritePackageJson(text, expected);
  const after = apply(state.packageJsonText);
  if (after === state.packageJsonText) return null;
  return {
    id: 'DEPS_TO_MATRIX',
    file: state.packageJsonPath || 'package.json',
    why: `Pin existing ${family} PCF dependency declarations to the compatibility matrix without moving user packages between dependency sections.`,
    apply,
  };
}

function rewritePackageJson(text, expected) {
  const parsed = JSON.parse(text);
  let changed = false;
  for (const section of ['dependencies', 'devDependencies']) {
    if (!parsed[section] || typeof parsed[section] !== 'object' || Array.isArray(parsed[section])) continue;
    const wanted = expected[section] || {};
    for (const name of Object.keys(parsed[section])) {
      if (!Object.hasOwn(wanted, name)) continue;
      if (parsed[section][name] !== wanted[name]) {
        parsed[section][name] = wanted[name];
        changed = true;
      }
    }
  }
  if (!changed) return text;
  // package.json is data, but hand-built controls often carry unrelated user dependencies. The
  // transform keeps the raw object insertion order emitted by JSON.parse/stringify:
  //   before: "dependencies": { "react": "^18.2.0", "left-pad": "1.3.0" }
  //   after:  "dependencies": { "react": "16.14.0", "left-pad": "1.3.0" }
  // Matrix packages already in dependencies/devDependencies are pinned in-place; unknown packages
  // are untouched and a package is never moved between sections, avoiding accidental runtime/dev
  // semantic changes in projects that were not generated by this skill.
  return `${JSON.stringify(parsed, null, 2)}${text.endsWith('\n') ? '\n' : ''}`;
}

function buildModeStep(state) {
  const text = state.pcfprojText || '';
  if (!text || pcfprojBuildMode(text).status === 'production') return null;
  return {
    id: 'BUILDMODE_PRODUCTION',
    file: state.pcfprojPath || '*.pcfproj',
    why: 'Move PcfBuildMode below Microsoft.Common.props so pac pcf push Debug builds produce production bundles.',
    apply: (source) => rewritePcfBuildMode(source),
  };
}

function rewritePcfBuildMode(text) {
  const source = String(text || '');
  let withoutMode = source.replace(/\r?\n[ \t]*<!-- pac pcf push otherwise builds[\s\S]*?-->\r?\n[ \t]*<PcfBuildMode>\s*[^<]+?\s*<\/PcfBuildMode>/i, '');
  withoutMode = withoutMode.replace(/\r?\n[ \t]*<PcfBuildMode>\s*[^<]+?\s*<\/PcfBuildMode>/i, '');
  const lineEnd = source.includes('\r\n') ? '\r\n' : '\n';
  const nameMatch = /(<Name>[^<]+<\/Name>)(\r?\n)([ \t]*)/.exec(withoutMode);
  if (nameMatch && afterCommonProps(withoutMode, nameMatch.index)) {
    const insertion = `${nameMatch[1]}${nameMatch[2]}${nameMatch[3]}<PcfBuildMode>production</PcfBuildMode>${nameMatch[2]}${nameMatch[3]}`;
    const after = `${withoutMode.slice(0, nameMatch.index)}${insertion}${withoutMode.slice(nameMatch.index + nameMatch[0].length)}`;
    assertEffectiveBuildMode(after);
    return after;
  }
  const importMatch = /<Import\b[^>]*\bProject\s*=\s*["'][^"']*Microsoft\.Common\.props["'][^"']*\/?>/i.exec(withoutMode);
  if (!importMatch) {
    const after = withoutMode.replace(/(<PropertyGroup\b[^>]*>)(\r?\n)([ \t]*)/, `$1$2$3<PcfBuildMode>production</PcfBuildMode>$2$3`);
    assertEffectiveBuildMode(after);
    return after;
  }
  const afterImport = importMatch.index + importMatch[0].length;
  const indent = leadingIndent(withoutMode, importMatch.index);
  const insertion = `${lineEnd}${indent}<PropertyGroup>${lineEnd}${indent}  <PcfBuildMode>production</PcfBuildMode>${lineEnd}${indent}</PropertyGroup>`;
  const after = `${withoutMode.slice(0, afterImport)}${insertion}${withoutMode.slice(afterImport)}`;
  assertEffectiveBuildMode(after);
  return after;
}

function afterCommonProps(text, offset) {
  const mode = pcfprojBuildMode(`${text.slice(0, offset)}<PcfBuildMode>production</PcfBuildMode>${text.slice(offset)}`);
  return mode.status === 'production';
}

function assertEffectiveBuildMode(text) {
  // Raw `.pcfproj` shape that matters:
  //   <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  //   <PropertyGroup><Name>StarRating</Name> ... </PropertyGroup>
  // Microsoft.PowerApps.MSBuild.Pcf props imported through Microsoft.Common.props reset Debug to
  // development, and pac pcf push builds Debug. The after-shape must therefore be:
  //   <Import ... Microsoft.Common.props />
  //   <PropertyGroup><Name>StarRating</Name><PcfBuildMode>production</PcfBuildMode> ...</PropertyGroup>
  // Use the doctor's one detector as the invariant so this transform cannot drift from diagnostics.
  const mode = pcfprojBuildMode(text);
  if (mode.status !== 'production') throw new Error('PcfBuildMode transform did not produce an effective production setting.');
}

function leadingIndent(text, offset) {
  const lineStart = text.lastIndexOf('\n', offset) + 1;
  const match = /^[ \t]*/.exec(text.slice(lineStart, offset));
  return match ? match[0] : '';
}

function platformLibrarySteps(state, matrix) {
  const out = [];
  for (const manifest of state.manifestFiles || []) {
    const after = rewritePlatformLibraries(manifest.text, matrix);
    if (after === manifest.text) continue;
    out.push({
      id: 'PLATFORM_LIB_VERSION',
      file: manifest.path,
      why: 'Align React and Fluent platform-library declarations to the compatibility matrix baseline without changing any other manifest bytes.',
      apply: (text) => rewritePlatformLibraries(text, matrix),
    });
  }
  return out;
}

function rewritePlatformLibraries(text, matrix) {
  const baselines = {
    React: matrix.platformLibraries.React.recommendedBaseline.version,
    Fluent: matrix.platformLibraries.Fluent.recommendedBaseline.version,
  };
  return String(text || '').replace(/<platform-library\b[^>]*>/g, (tag) => {
    const name = attrFromTag(tag, 'name');
    const current = attrFromTag(tag, 'version');
    if (!Object.hasOwn(baselines, name)) return tag;
    if (name === 'Fluent' && /^8\./.test(String(current || ''))) return tag;
    if (current === baselines[name]) return tag;
    // Manifest platform-library tags are transformed as a byte-preserving targeted attribute edit:
    //   before: <platform-library name="Fluent" version="9.68.0" />
    //   after:  <platform-library name="Fluent" version="9.46.2" />
    // React/Fluent package family and declaration semantics are separate decisions; this low-risk
    // step only changes the version attribute on already-declared React or Fluent platform libraries.
    return tag.replace(/(\bversion\s*=\s*["'])([^"']*)(["'])/, `$1${baselines[name]}$3`);
  });
}

function attrFromTag(tag, name) {
  const re = new RegExp(`\\b${name}\\s*=\\s*["']([^"']*)["']`, 'i');
  const match = re.exec(tag);
  return match ? match[1] : '';
}

function addManualNotes(state, hosts, manual) {
  const family = dependencyFamily(state);
  const declared = (state.manifestModels || []).flatMap((model) => (model.resources && model.resources.platformLibraries) || []);
  if (family === 'standard' && declared.some((lib) => lib.name === 'React' || lib.name === 'Fluent')) {
    manual.push({
      id: 'STANDARD_TO_VIRTUAL',
      why: 'Changing a standard control to virtual changes runtime shape and is not applied automatically.',
      refs: [BEST_PRACTICES, UPGRADE_FLOW],
    });
  }
  if (declared.some((lib) => lib.name === 'Fluent' && /^8\./.test(String(lib.version || '')))) {
    manual.push({
      id: 'FLUENT_8_TO_9',
      why: 'Moving Fluent 8 controls to Fluent 9 can require code and styling changes, so the planner leaves it as a manual upgrade.',
      refs: [BEST_PRACTICES, UPGRADE_FLOW],
    });
  }
  if (hosts.includes('pages') && family === 'virtual') {
    manual.push({
      id: 'PAGES_VIRTUAL_TO_STANDARD',
      why: 'Power Pages supports standard PCF controls and does not support virtual platform-library declarations.',
      refs: [BEST_PRACTICES, UPGRADE_FLOW],
    });
  }
}

function serializePlan(plan) {
  return {
    steps: (plan.steps || []).map(({ apply, ...step }) => step),
    manual: plan.manual || [],
  };
}

function applyUpgrade(plan, projectDir, deps = {}) {
  const fsDep = deps.fs || fs;
  const runNpm = deps.runNpm || defaultRunNpm;
  const applied = [];
  const skipped = [];
  const safeProject = fsDep.realpathSync(projectDir);

  for (const step of plan.steps || []) {
    if (!SAFE_APPLY.has(step.id)) {
      skipped.push(step.id);
      continue;
    }
    if (step.id === 'REINSTALL') {
      if (deps.noInstall) {
        skipped.push('REINSTALL: run npm install in the PCF project');
        continue;
      }
      const install = runNpm(['install'], { cwd: projectDir, npmCli: deps.npmCli });
      if (install.status !== 0) {
        const detail = [install.stderr, install.stdout, install.error].filter(Boolean).join('\n').trim();
        throw new Error(`npm install failed${detail ? `:\n${detail}` : ''}`);
      }
      applied.push(step.id);
      continue;
    }
    if (typeof step.apply !== 'function') {
      skipped.push(step.id);
      continue;
    }
    const file = resolveProjectFile(step.file, safeProject);
    const before = fsDep.readFileSync(file, 'utf8');
    const after = step.apply(before);
    if (after !== before) fsDep.writeFileSync(file, after);
    applied.push(step.id);
  }
  return { applied, skipped };
}

function resolveProjectFile(file, projectDir) {
  const resolved = path.resolve(String(file));
  const project = path.resolve(projectDir);
  const rel = path.relative(project, resolved);
  if (rel === '' || rel.startsWith('..') || path.isAbsolute(rel)) {
    throw new Error(`Refusing to write outside the PCF project: ${file}`);
  }
  return resolved;
}

function collectUpgradeState(projectDir, deps = {}) {
  const fsDep = deps.fs || fs;
  const found = findControlProject(projectDir, deps);
  if (found.error) throw new Error(found.error);
  const state = collectProject(found.projectDir, deps);
  state.packageJsonPath = found.packageJson;
  state.packageJsonText = fsDep.readFileSync(found.packageJson, 'utf8');
  state.pcfprojPath = found.pcfproj;
  state.pcfprojText = fsDep.readFileSync(found.pcfproj, 'utf8');
  state.manifestFiles = found.manifests.map((file) => {
    const text = fsDep.readFileSync(file, 'utf8');
    return { path: file, text, model: parseManifest(text).model };
  });
  return state;
}

function dirtyTreeStatus(projectDir, deps = {}) {
  const spawnSync = deps.spawnSync || defaultSpawnSync;
  const result = spawnSync('git', ['status', '--porcelain', '--', projectDir], {
    cwd: projectDir,
    encoding: 'utf8',
    shell: false,
    windowsHide: true,
  });
  if (result.status !== 0) {
    const detail = String(result.stderr || result.error || '').trim();
    return {
      ok: false,
      error: `Refusing to apply because '${projectDir}' is not inside a readable git work tree. Commit first or pass --allow-dirty.${detail ? ` ${detail}` : ''}`,
    };
  }
  if (String(result.stdout || '').trim()) {
    return {
      ok: false,
      error: 'Refusing to apply because the project has uncommitted changes. Commit, stash, or pass --allow-dirty.',
    };
  }
  return { ok: true };
}

function runUpgrade(options = {}, deps = {}) {
  const projectDir = path.resolve(String(options.project || process.cwd()));
  const matrix = deps.matrix || loadMatrix();
  const hosts = options.hosts || ['model'];
  const beforeState = collectUpgradeState(projectDir, deps);
  const before = checkProject(beforeState, matrix, { hosts, needs: ['build'] });
  const plan = planUpgrade(beforeState, matrix, { hosts });
  let applied = [];
  let skipped = [];
  let after = null;
  let ok = true;

  if (options.apply) {
    if (!options.allowDirty) {
      const dirty = dirtyTreeStatus(projectDir, deps);
      if (!dirty.ok) {
        return { ok: false, error: dirty.error, plan: serializePlan(plan), applied, skipped, manual: plan.manual, before, after };
      }
    }
    const result = applyUpgrade(plan, projectDir, {
      ...deps,
      noInstall: options.noInstall,
      npmCli: options.npmCli,
    });
    applied = result.applied;
    skipped = result.skipped;
    const afterState = collectUpgradeState(projectDir, deps);
    after = checkProject(afterState, matrix, { hosts, needs: ['build'] });
    ok = !hasErrors(after);
  }

  return {
    ok,
    plan: serializePlan(plan),
    applied,
    skipped,
    manual: plan.manual,
    before,
    after,
  };
}

module.exports = {
  planUpgrade,
  applyUpgrade,
  collectUpgradeState,
  dirtyTreeStatus,
  runUpgrade,
  rewritePackageJson,
  rewritePcfBuildMode,
  rewritePlatformLibraries,
};
