'use strict';

const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');

const script = path.resolve(__dirname, '..', 'cleanup-prototype-artifacts.js');
const marker = '// Generated by create-mobile-prototype/gen-mock-services.js\n';

function makeProject(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'prototype-cleanup-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const files = {
    'package.json': '{}\n',
    'src/generated/.prototype-manifest.json': '{"schemaVersion":1}\n',
    'src/generated/services/Cr_task.seed.json': '[]\n',
    'src/generated/services/Cr_taskService.ts': `${marker}// In-memory prototype service.\n`,
    'src/generated/services/dataSourcesInfo.ts': marker,
    'src/generated/schemas/Cr_task.Schema.ts': marker,
  };
  for (const [relativePath, contents] of Object.entries(files)) {
    const filePath = path.join(root, relativePath);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, contents);
  }
  return root;
}

function run(root, ...args) {
  return spawnSync(process.execPath, [script, root, ...args], { encoding: 'utf8' });
}

test('check mode reports prototype artifacts without deleting them', (t) => {
  const root = makeProject(t);
  const result = run(root, '--check');
  assert.equal(result.status, 2);
  assert.match(result.stdout, /2 removable artifact\(s\)/);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/services/Cr_task.seed.json')), true);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/schemas/Cr_task.Schema.ts')), true);
});

test('mutation mode deletes only safe artifacts and blocks on a surviving mock service', (t) => {
  const root = makeProject(t);
  const result = run(root);
  assert.equal(result.status, 2);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/services/Cr_task.seed.json')), false);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/schemas/Cr_task.Schema.ts')), false);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/services/Cr_taskService.ts')), true);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/.prototype-manifest.json')), true);
  assert.match(result.stderr, /mock-marker: src\/generated\/services\/Cr_taskService\.ts/);
});

test('passes and removes the prototype manifest after real services replace every mock', (t) => {
  const root = makeProject(t);
  fs.writeFileSync(path.join(root, 'src/generated/services/Cr_taskService.ts'), '// Real generated Dataverse service.\n');
  fs.writeFileSync(path.join(root, 'src/generated/services/dataSourcesInfo.ts'), '// Real generated service registry.\n');

  const result = run(root);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /prototype-cleanup: PASS/);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/services/Cr_task.seed.json')), false);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/schemas/Cr_task.Schema.ts')), false);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/.prototype-manifest.json')), false);
  assert.equal(fs.existsSync(path.join(root, 'src/generated/services/Cr_taskService.ts')), true);
});