#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { spawn, spawnSync } = require('node:child_process');
const { parseTable } = require('../../../scripts/validate-screen-contracts');

const DEBOUNCE_MS = 500;
const METRO_READY_BUDGET_MS = 30000;
const PLUGIN_ROOT = path.resolve(__dirname, '..', '..', '..');
const TEMPLATE_ROOT = path.join(PLUGIN_ROOT, 'template');
const INSTALLER = path.join(__dirname, 'install-dependencies.js');

function sleep(milliseconds) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, milliseconds);
}

function atomicWrite(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const temporary = `${filePath}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(temporary, contents);
  fs.renameSync(temporary, filePath);
}

function atomicJson(filePath, value) {
  atomicWrite(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function buildPaths(projectDir) {
  const buildDir = path.join(projectDir, '.mobile-build');
  return {
    buildDir,
    backupIndex: path.join(buildDir, 'index.backup.tsx'),
    buildingRoute: path.join(projectDir, 'app', 'building.tsx'),
    log: path.join(buildDir, 'metro.log'),
    progressModule: path.join(projectDir, 'src', 'generated', 'buildProgress.ts'),
    state: path.join(buildDir, 'supervisor.json'),
  };
}

function initialState(projectDir) {
  return {
    schemaVersion: 1,
    startedAt: new Date().toISOString(),
    projectDir,
    trackA: 'starting',
    metro: { state: 'queued', pid: null, url: null },
    screens: [
      { id: 'brief', label: 'Understanding your brief', state: 'built' },
      { id: 'plan', label: 'Planning data and screens', state: 'building' },
      { id: 'screens', label: 'Building screens', state: 'queued' },
      { id: 'quality', label: 'Checking quality', state: 'queued' },
    ],
    concerns: [],
    lastShellWriteAt: 0,
  };
}

function readState(projectDir) {
  const filePath = buildPaths(projectDir).state;
  return fs.existsSync(filePath) ? JSON.parse(fs.readFileSync(filePath, 'utf8')) : initialState(projectDir);
}

function writeState(projectDir, state) {
  atomicJson(buildPaths(projectDir).state, state);
}

function slug(value) {
  return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'screen';
}

function defaultTokens() {
  return `// Generated by generate-prototype-design-system.js as the pre-plan shell baseline.
export const tokens = {
  color: { bg: '#F8FAFC', surface: '#FFFFFF', surfaceMuted: '#E8EEF4', border: '#CFD8E3', primary: '#0A4F8F', primaryStrong: '#073968', accent: '#D6E4F2', onPrimary: '#FFFFFF', text: '#10243B', textMuted: '#526579', statusSuccess: '#137333', statusWarning: '#B06000', statusDanger: '#C5221F', statusInfo: '#1A73E8' },
  space: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, '2xl': 32, '3xl': 48, '4xl': 64 },
  size: { buttonHeight: 52, inputHeight: 52, listRowHeight: 64, iconSize: 24, avatarSm: 32, avatarMd: 40, avatarLg: 56 },
  radius: { sm: 4, md: 8, lg: 12, full: 24 },
} as const;
export const typeScale = {
  headlineLarge: { fontSize: 32, lineHeight: 40, fontWeight: '400' },
  headlineMedium: { fontSize: 28, lineHeight: 36, fontWeight: '400' },
  headlineSmall: { fontSize: 24, lineHeight: 32, fontWeight: '400' },
  titleLarge: { fontSize: 22, lineHeight: 28, fontWeight: '500' },
  bodyLarge: { fontSize: 16, lineHeight: 24, fontWeight: '400' },
  bodyMedium: { fontSize: 14, lineHeight: 20, fontWeight: '400' },
  labelSmall: { fontSize: 11, lineHeight: 16, fontWeight: '500' },
} as const;
export const shapeScale = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24 } as const;
export const fontStack = { heading: 'Avenir Next, Avenir, Segoe UI, sans-serif', body: 'Avenir Next, Avenir, Segoe UI, sans-serif', mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace' } as const;
`;
}

function progressModule(state) {
  return `// Generated atomically by the prototype supervisor.\nexport type BuildScreenState = 'queued' | 'building' | 'written' | 'checked' | 'built' | 'failed';\nexport const buildProgress: ReadonlyArray<{ id: string; label: string; state: BuildScreenState; file?: string }> = ${JSON.stringify(state.screens, null, 2)};\n`;
}

function buildingRoute() {
  return `import { ScrollView, Text, View } from 'react-native';
import { buildProgress } from '../src/generated/buildProgress';
import { tokens, typeScale } from '../brand/tokens';

const marker = { built: '[x]', checked: '[x]', written: '[~]', building: '[~]', queued: '[ ]', failed: '[!]' } as const;

export default function BuildingApp() {
  return (
    <ScrollView style={{ flex: 1, backgroundColor: tokens.color.bg }} contentContainerStyle={{ padding: tokens.space.xl, paddingTop: tokens.space['3xl'], gap: tokens.space.lg }}>
      <Text style={{ color: tokens.color.text, fontSize: typeScale.headlineLarge.fontSize, lineHeight: typeScale.headlineLarge.lineHeight }}>Building your app</Text>
      <Text style={{ color: tokens.color.textMuted, fontSize: typeScale.bodyMedium.fontSize, lineHeight: typeScale.bodyMedium.lineHeight }}>Screens appear here as they are checked.</Text>
      <View style={{ backgroundColor: tokens.color.surface, borderRadius: tokens.radius.lg, padding: tokens.space.lg, gap: tokens.space.md }}>
        {buildProgress.map((item) => (
          <View key={item.id} style={{ flexDirection: 'row', gap: tokens.space.md, alignItems: 'center' }}>
            <Text style={{ color: item.state === 'failed' ? tokens.color.statusDanger : tokens.color.primary }}>{marker[item.state]}</Text>
            <Text style={{ color: tokens.color.text, fontSize: typeScale.bodyLarge.fontSize, lineHeight: typeScale.bodyLarge.lineHeight }}>{item.label}</Text>
          </View>
        ))}
      </View>
    </ScrollView>
  );
}
`;
}

function shellIndex() {
  return `import { Redirect } from 'expo-router';\n\nexport default function Index() {\n  return <Redirect href="/building" />;\n}\n`;
}

function writeShell(projectDir, state) {
  const paths = buildPaths(projectDir);
  const tokenPath = path.join(projectDir, 'brand', 'tokens.ts');
  if (!fs.existsSync(tokenPath)) atomicWrite(tokenPath, defaultTokens());
  atomicWrite(paths.progressModule, progressModule(state));
  atomicWrite(paths.buildingRoute, buildingRoute());
  const indexPath = path.join(projectDir, 'app', 'index.tsx');
  if (!fs.existsSync(paths.backupIndex)) atomicWrite(paths.backupIndex, fs.readFileSync(indexPath, 'utf8'));
  atomicWrite(indexPath, shellIndex());
  state.lastShellWriteAt = Date.now();
  writeState(projectDir, state);
}

function materialize(projectDir) {
  const packagePath = path.join(projectDir, 'package.json');
  if (fs.existsSync(packagePath)) return false;
  fs.mkdirSync(projectDir, { recursive: true });
  const entries = fs.readdirSync(projectDir);
  if (entries.length > 0) throw new Error(`cannot materialize template into non-empty ${projectDir}`);
  fs.cpSync(TEMPLATE_ROOT, projectDir, {
    recursive: true,
    filter: (source) => path.basename(source) !== 'node_modules',
  });
  return true;
}

function install(projectDir) {
  if (fs.existsSync(path.join(projectDir, 'node_modules', 'expo'))) return;
  const result = spawnSync(process.execPath, [INSTALLER, projectDir], { encoding: 'utf8' });
  if (result.status !== 0) throw new Error(`dependency install failed: ${result.stderr || result.stdout}`);
}

function processAlive(pid) {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function startMetro(projectDir, port, state) {
  const paths = buildPaths(projectDir);
  const expoCli = path.join(projectDir, 'node_modules', 'expo', 'bin', 'cli');
  const logFd = fs.openSync(paths.log, 'a');
  const child = spawn(process.execPath, [expoCli, 'start', '--port', String(port)], {
    cwd: projectDir,
    detached: true,
    env: { ...process.env, EXPO_NO_DOCTOR: '1' },
    stdio: ['ignore', logFd, logFd],
  });
  child.unref();
  state.metro = { state: 'starting', pid: child.pid, url: null };
  writeState(projectDir, state);
  const deadline = Date.now() + METRO_READY_BUDGET_MS;
  while (Date.now() < deadline && processAlive(child.pid)) {
    const log = fs.existsSync(paths.log) ? fs.readFileSync(paths.log, 'utf8') : '';
    const url = log.match(/(?:exp(?:\+[^:]+)?|http):\/\/[^\s]+/)?.[0] || null;
    if (/Metro waiting on|Waiting on http|Logs for your project/.test(log)) {
      state.metro = { state: 'ready', pid: child.pid, url };
      writeState(projectDir, state);
      return;
    }
    sleep(250);
  }
  throw new Error(processAlive(child.pid) ? 'Metro did not become ready within 30 seconds' : 'Metro exited before becoming ready');
}

function addConcern(state, concern) {
  if (!state.concerns.includes(concern)) state.concerns.push(concern);
}

function start(projectDir, { noMetro = false, port = 8081 } = {}) {
  materialize(projectDir);
  const state = readState(projectDir);
  writeShell(projectDir, state);
  try {
    install(projectDir);
  } catch (error) {
    addConcern(state, error.message);
  }
  if (noMetro) {
    state.metro.state = 'disabled';
  } else if (state.concerns.length === 0) {
    try {
      startMetro(projectDir, port, state);
    } catch (error) {
      addConcern(state, error.message);
      state.metro.state = 'failed';
    }
  }
  state.trackA = state.concerns.length > 0 ? 'degraded' : 'ready';
  writeState(projectDir, state);
  return state;
}

function prepareRuntime(projectDir) {
  const paths = buildPaths(projectDir);
  if (!fs.existsSync(paths.backupIndex)) throw new Error('supervisor index backup is missing');
  atomicWrite(path.join(projectDir, 'app', 'index.tsx'), fs.readFileSync(paths.backupIndex, 'utf8'));
}

function planScreens(projectDir, planPath) {
  const state = readState(projectDir);
  const markdown = fs.readFileSync(planPath, 'utf8');
  const errors = [];
  const table = parseTable(markdown, '### Screen Map', errors);
  if (errors.length > 0 || !table.headers.includes('Screen') || !table.headers.includes('File')) {
    throw new Error(errors.join('; ') || 'Screen Map is missing Screen/File columns');
  }
  state.screens = table.rows
    .map((row) => Object.fromEntries(table.headers.map((header, index) => [header, row[index] || ''])))
    .filter((row) => row.File.startsWith('app/(app)/'))
    .map((row) => ({ id: slug(row.Screen), label: row.Screen, state: 'queued', file: row.File }));
  writeState(projectDir, state);
  atomicWrite(buildPaths(projectDir).progressModule, progressModule(state));
  return state;
}

function updateScreen(projectDir, id, screenState) {
  const state = readState(projectDir);
  const screen = state.screens.find((candidate) => candidate.id === id);
  if (!screen) throw new Error(`unknown screen ${id}`);
  screen.state = screenState;
  const elapsed = Date.now() - state.lastShellWriteAt;
  if (elapsed < DEBOUNCE_MS) sleep(DEBOUNCE_MS - elapsed);
  state.lastShellWriteAt = Date.now();
  atomicWrite(buildPaths(projectDir).progressModule, progressModule(state));
  writeState(projectDir, state);
}

function release(projectDir, route) {
  const modePath = path.join(projectDir, 'src', 'config', 'dataMode.ts');
  const source = fs.readFileSync(modePath, 'utf8');
  if (!source.includes('prototypeEntryRoute')) throw new Error('prototypeEntryRoute is missing');
  atomicWrite(modePath, source.replace(/prototypeEntryRoute\s*=\s*[^;]+;/, `prototypeEntryRoute = ${JSON.stringify(route)} as const;`));
  const state = readState(projectDir);
  state.releasedRoute = route;
  writeState(projectDir, state);
}

function status(projectDir) {
  const state = readState(projectDir);
  if (state.metro.state === 'ready' && !processAlive(state.metro.pid)) {
    state.metro.state = 'failed';
    addConcern(state, 'Metro stopped before the build completed; continuing in text-only mode');
    writeState(projectDir, state);
  }
  return state;
}

function parseArgs(argv) {
  const [command, projectArg] = argv;
  if (!command || !projectArg) throw new Error('usage: supervisor.js <start|prepare-runtime|plan|screen|release|status> <project-dir> [options]');
  const option = (name) => {
    const index = argv.indexOf(name);
    return index >= 0 ? argv[index + 1] : null;
  };
  return { command, projectDir: path.resolve(projectArg), option, argv };
}

function printResult(state) {
  const statusName = state.concerns.length > 0 ? 'DONE_WITH_CONCERNS' : 'DONE';
  console.log(JSON.stringify({ status: statusName, concerns: state.concerns, metro: state.metro, screens: state.screens }));
}

function main() {
  try {
    const args = parseArgs(process.argv.slice(2));
    let state;
    if (args.command === 'start') state = start(args.projectDir, { noMetro: args.argv.includes('--no-metro'), port: Number(args.option('--port') || 8081) });
    else if (args.command === 'prepare-runtime') { prepareRuntime(args.projectDir); state = readState(args.projectDir); }
    else if (args.command === 'plan') state = planScreens(args.projectDir, path.resolve(args.option('--plan')));
    else if (args.command === 'screen') { updateScreen(args.projectDir, args.option('--id'), args.option('--state')); state = readState(args.projectDir); }
    else if (args.command === 'release') { release(args.projectDir, args.option('--route')); state = readState(args.projectDir); }
    else if (args.command === 'status') state = status(args.projectDir);
    else throw new Error(`unknown supervisor command ${args.command}`);
    printResult(state);
  } catch (error) {
    console.error(`prototype-supervisor: ${error.message}`);
    process.exit(1);
  }
}

if (require.main === module) main();

module.exports = { DEBOUNCE_MS, METRO_READY_BUDGET_MS, atomicWrite, buildPaths, materialize, planScreens, processAlive, release, start, status, updateScreen };